name: Create GCP Bucket with Workload Identity Federation

on:
  push:
    branches:
      - main # Or your main branch

jobs:
  create-bucket:
    runs-on: ubuntu-latest
    permissions:
      contents: read # For checking out the code

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: Authenticate to GCP with Workload Identity Federation
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }} # Store your WIF config in secrets

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Create GCP Bucket
        run: |
          BUCKET_NAME="my-unique-bucket-${GITHUB_RUN_ID}" # Use a unique name
          gsutil mb -p ${{ secrets.GCP_PROJECT_ID }} gs://${BUCKET_NAME}
          echo "Bucket created: gs://${BUCKET_NAME}"

      - name: Verify Bucket Creation (Optional)
        run: |
          gsutil ls gs://${BUCKET_NAME}
