name: Create GCP Bucket with Workload Identity Federation

on:
  push:
    branches:
      - main

jobs:
  create-bucket:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: Authenticate to GCP with Workload Identity Federation
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WORKLOAD_IDENTITY_POOL_ID }}/providers/${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Print Attributes
        run: |
          echo "Id Token: ${{ steps.auth.outputs.id_token }}"
          echo "Context: ${{ toJson(github.context) }}"

      - name: Set GCP Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }} # Set the project

      - name: Create GCP Bucket
        run: |
          BUCKET_NAME="my-unique-bucket-${GITHUB_RUN_ID}"
          gsutil mb gs://${BUCKET_NAME} # Project is already set
          echo "Bucket created: gs://${BUCKET_NAME}"

      - name: Verify Bucket Creation (Optional)
        run: |
          gsutil ls gs://${BUCKET_NAME}
